export default {
	SIGNUP: 'SIGN UP FOR THE TLC NEWSLETTER',
	SIGNUP2: `SIGN UP FOR${'\n'}THE TLC NEWSLETTER`,
	JOIN: 'join the list',
	NEXT: 'NEXT',
	ENTER_EMAIL: 'enter email address',
	CONGRATULATIONS: 'congratulations!',
	POLICY: `I agree to receive information from ${'\n'}Discovery Communications in accordance ${'\n'}with the following `,
	POLICY2: `I agree to receive information from Discovery Communications${'\n'}in accordance with the following `,
	ALMOST_DONE: `ALMOST DONE! PLEASE ENTER ${'\n'}YOUR FIRST AND LAST NAME.`,
	ALMOST_DONE2: `ALMOST DONE! PLEASE ENTER YOUR FIRST AND LAST NAME.`,
	FIRST_NAME: 'First Name',
	LAST_NAME: 'Last Name',
	SIGN_UP: 'SIGN UP',
	THANK_YOU: `Thank You For${'\n'}Signing Up!`,
	LOOK_OUT: `Look out for the latest news on\n your favorite shows.`,
	THANK_YOU2: `Thank You For Signing Up!`,
	LOOK_OUT2: `Look out for the latest news on your favorite shows.`,
}
